### ISSUE TITLE
Error when opening the ModuleManagement dialog

### ISSUE THREAD

**Issue by ghost91-** [mouse0270/module-credits#40]
With MM+ installed on foundry v9.269, when opening the `ModuleManagement` dialog, the following error is shown:
```
foundry.js:297 Foundry VTT | Error thrown in hooked function 'renderModuleManagement' for hook 'renderModuleManagement'
_call @ foundry.js:297
call @ foundry.js:279
_render @ foundry.js:3117
await in _render (async)
_render @ foundry.js:3764
render @ foundry.js:3021
_onSettingsButton @ foundry.js:60260
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:319 TypeError: Cannot read properties of undefined (reading 'TagVersion')
    at Function.fixModuleTags (module.mjs:476:63)
    at renderModuleManagement (module.mjs:920:9)
    at Function._call (foundry.js:294:14)
    at Function.call (foundry.js:279:33)
    at ModuleManagement._render (foundry.js:3117:13)
    at async ModuleManagement._render (foundry.js:3764:5)
onError @ foundry.js:319
_call @ foundry.js:298
call @ foundry.js:279
_render @ foundry.js:3117
await in _render (async)
_render @ foundry.js:3764
render @ foundry.js:3021
_onSettingsButton @ foundry.js:60260
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

**Comment by mouse0270** [comment]
This appears to be an issue with foundry's translation. This is outdated logic and shouldn't matter.

Also fixed in v2 for foundery v10
