### ISSUE TITLE
Unable to load Module Management+ dialog

### ISSUE THREAD

**Issue by etriebe** [mouse0270/module-credits#44]
Happens with latest version off MM+

```
foundry.js:319 
        
       TypeError: Cannot read properties of undefined (reading 'verified')
[Detected 1 package: quick-module-enable]
    at ModuleManagement.getQuickEnableData (index.js:113:94)
    at ModuleManagement._render (foundry.js:3062:29)
    at ModuleManagement._render (foundry.js:3764:17)
    at ModuleManagement.render (foundry.js:3021:10)
    at Settings._onSettingsButton (foundry.js:60260:32)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
```

**Comment by etriebe** [comment]
Think this was due to quick module enable module.

**Comment by mouse0270** [comment]
These two modules should work together in version 2.0.0+
